version: '3'

services:
  mosquitto:
    image: akbennett/simple-mosquitto-broker:latest
    read_only: true
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - big-network
    restart: always

  nginx-http-proxy:
    image: akbennett/simple-http-proxy:latest
    tmpfs:
      - /run
      - /var/run
      - /var/cache/nginx
    read_only: true
    ports:
      - "8080:8080"
    networks:
      - big-network
    extra_hosts:
      - "mgmt.foundries.io:192.168.0.50"
    restart: always

  bt-joiner:
    image: akbennett/simple-bt-joiner:latest
    tmpfs:
      - /run
      - /var/lock
      - /var/log
      - /var/run
    network_mode: "host"
    restart: always
    read_only: true
    privileged: true

  simple-coap-proxy:
    image: akbennett/simple-coap-proxy:latest
    tmpfs:
      - /run
      - /var/run
      - /var/cache/nginx
    read_only: true
    ports:
      - "8080:8080"
    extra_hosts:
      - "mgmt.foundries.io:192.168.0.50"
    ports:
      - "5683:5683/udp"
      - "5684:5684/udp"
      - "5685:5685/udp"
      - "5686:5686/udp"
    networks:
      - big-network
    restart: always

 simple-californium-proxy:
    image: akbennett/simple-californium-proxy:latest
    read_only: true
    ports:
      - "5682:5682"
    networks:
      - big-network
    restart: always

networks:
  big-network:
